### ISSUE TITLE
issue with installation 

### ISSUE THREAD

**Issue by mounaBoo** [0xxon/zeek-postgresql#3]
hello, 
I have a questio about the installation when I tape the command: 

zkg install zeek-postgresql 

it shows me this error:

```
OSError: [Errno 13] Permission denied: '/opt/zeek/lib/zeek'
error: user does not have write access in /opt/zeek/lib/zeek/plugins
```

could anyone help me please.

**Comment by 0xxon** [comment]
Sorry - I totally did not notice it. This is just a linux permission problem - you need to make the installation as a user that has write access to the named folder.

**Comment by XiaoyiGao** [comment]
I have one question. Could you help me?
error: invalid package "0xxon/bro-postgresql": package name not found in sources and also not a usable git URL (invalid or inaccessible, use -vvv for details)
